spring.application.name=insta-clone-backend

spring.datasource.url=jdbc:h2:file:C:/dataprojectspring/insta-test-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#MINIO CONFIGURATION
# Minio server
minio.url=http://localhost:9000
minio.accessKey=instaminio
minio.secretKey=instaminio2025
minio.bucketName=files

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


#JWT CONFIGURATIONS
application.security.jwt.secret-key: 61044005042533385d3cc6d2a32c72c62da5664619cd3dfa9125f13278884082
application.security.jwt.expiration: 84600000
application.security.jwt.refresh-token.expiration: 604800000


server.port=8090